[package]
name = "ssmp-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"          # codec
bytes = "1.4"
futures = "0.3"
clap = { version = "4", features = ["derive"] }
